# Generated by Django 4.2.7 on 2023-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='response',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ почтового сервера'),
        ),
    ]
