# Generated by Django 4.2.7 on 2023-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_logs_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='interval',
            field=models.CharField(choices=[('once_a_day', 'once_a_day'), ('once_a_week', 'once_a_week'), ('once_a_month', 'once_a_month')], default='разовая', max_length=50, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('finish', 'finish'), ('created', 'created')], help_text='Выберите Создана или Завершена', max_length=50),
        ),
    ]
